// <auto-generated />
using LogoQuiz.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LogoQuiz.Migrations
{
    [DbContext(typeof(Repository))]
    partial class RepositoryModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("LogoQuiz.Models.Logo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSucceed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Level")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Point")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Logos");

                    b.HasData(
                        new
                        {
                            Id = "15034BCC049F4DBDA7AFA082587EDAC4",
                            ImageUrl = "barbie.jpg",
                            IsSucceed = false,
                            Level = "Level 1",
                            Name = "Barbie",
                            Point = 0
                        },
                        new
                        {
                            Id = "1DFF44ACEAF54E2A89B84AA5CABAE291",
                            ImageUrl = "baskin-robbins.jpg",
                            IsSucceed = false,
                            Level = "Level 1",
                            Name = "Baskin Robbins",
                            Point = 0
                        },
                        new
                        {
                            Id = "D20BE09757B5475DBC7370BFDE41BE0E",
                            ImageUrl = "budget.jpg",
                            IsSucceed = false,
                            Level = "Level 1",
                            Name = "Budget",
                            Point = 0
                        },
                        new
                        {
                            Id = "0472D95445F14F5F90E343126A7E0F20",
                            ImageUrl = "carlsberg.jpg",
                            IsSucceed = false,
                            Level = "Level 1",
                            Name = "Carlsberg",
                            Point = 0
                        },
                        new
                        {
                            Id = "55B29D7C2CEB409987CCFEB21BAF574E",
                            ImageUrl = "dunkin-donuts.jpg",
                            IsSucceed = false,
                            Level = "Level 1",
                            Name = "Dunkin Donuts",
                            Point = 0
                        },
                        new
                        {
                            Id = "B9F385FAFF6F4B28884AC65AE1A1CF42",
                            ImageUrl = "facebook.jpg",
                            IsSucceed = false,
                            Level = "Level 1",
                            Name = "Facebook",
                            Point = 0
                        },
                        new
                        {
                            Id = "EF229C0338144FC0BACCFB253AAA60CB",
                            ImageUrl = "fedex.jpg",
                            IsSucceed = false,
                            Level = "Level 1",
                            Name = "Fedex",
                            Point = 0
                        },
                        new
                        {
                            Id = "6090AA4EB12B4A01B18E2A5674C280CE",
                            ImageUrl = "holiday-inn.jpg",
                            IsSucceed = false,
                            Level = "Level 1",
                            Name = "Holiday inn",
                            Point = 0
                        },
                        new
                        {
                            Id = "1DDD220455174CE8AEC5D995D32BD3E5",
                            ImageUrl = "jaguar.jpg",
                            IsSucceed = false,
                            Level = "Level 1",
                            Name = "Jaguar",
                            Point = 0
                        },
                        new
                        {
                            Id = "997D51A2E01E4F4084862ECDA42DA79D",
                            ImageUrl = "kfc.jpg",
                            IsSucceed = false,
                            Level = "Level 1",
                            Name = "Kfc",
                            Point = 0
                        },
                        new
                        {
                            Id = "45F49AB9FE8C40568AFAF20D62F9AFAC",
                            ImageUrl = "knorr.jpg",
                            IsSucceed = false,
                            Level = "Level 1",
                            Name = "Knorr",
                            Point = 0
                        },
                        new
                        {
                            Id = "C4088080669A429EB9D116246A46E05A",
                            ImageUrl = "lexus.jpg",
                            IsSucceed = false,
                            Level = "Level 1",
                            Name = "Lexus",
                            Point = 0
                        },
                        new
                        {
                            Id = "BF8F1ABE99534781B304EC38D7C25817",
                            ImageUrl = "mcdonalds.jpg",
                            IsSucceed = false,
                            Level = "Level 1",
                            Name = "McDonalds",
                            Point = 0
                        },
                        new
                        {
                            Id = "E4D696C2AC384522A432A963D7680AE9",
                            ImageUrl = "pepsi.jpg",
                            IsSucceed = false,
                            Level = "Level 1",
                            Name = "Pepsi",
                            Point = 0
                        },
                        new
                        {
                            Id = "865E5B4CD3F64FEBA046DBF9F5C3E6F4",
                            ImageUrl = "playboy.jpg",
                            IsSucceed = false,
                            Level = "Level 1",
                            Name = "Playboy",
                            Point = 0
                        },
                        new
                        {
                            Id = "7133B90EE0B44821A5EABE9FABDE370A",
                            ImageUrl = "playstation.jpg",
                            IsSucceed = false,
                            Level = "Level 1",
                            Name = "PlayStation",
                            Point = 0
                        },
                        new
                        {
                            Id = "8EDCB1EF9AE045EE8FBE28DD9D8DF775",
                            ImageUrl = "safeway.jpg",
                            IsSucceed = false,
                            Level = "Level 1",
                            Name = "Safeway",
                            Point = 0
                        },
                        new
                        {
                            Id = "69B1FC49F0164994B1377C0EAB27F9C9",
                            ImageUrl = "the-body-shop.jpg",
                            IsSucceed = false,
                            Level = "Level 1",
                            Name = "The Body Shop",
                            Point = 0
                        },
                        new
                        {
                            Id = "56B7D1D668CE4C30BD3AA4BD007ACEC8",
                            ImageUrl = "visa.jpg",
                            IsSucceed = false,
                            Level = "Level 1",
                            Name = "Visa",
                            Point = 0
                        },
                        new
                        {
                            Id = "D3872929E64A48058ECF8E32AC5348E4",
                            ImageUrl = "yahoo.jpg",
                            IsSucceed = false,
                            Level = "Level 1",
                            Name = "Yahoo",
                            Point = 0
                        },
                        new
                        {
                            Id = "F21896755A764C3AB5494C71F1D1F840",
                            ImageUrl = "20th-century-fox.jpg",
                            IsSucceed = false,
                            Level = "Level 2",
                            Name = "20th Century Fox",
                            Point = 0
                        },
                        new
                        {
                            Id = "1164603623424F64A3897F5B2CD20FBF",
                            ImageUrl = "absolut.jpg",
                            IsSucceed = false,
                            Level = "Level 2",
                            Name = "Absolut",
                            Point = 0
                        },
                        new
                        {
                            Id = "00268E2059F140A384E0B7F81574787D",
                            ImageUrl = "adidas.jpg",
                            IsSucceed = false,
                            Level = "Level 2",
                            Name = "Adidas",
                            Point = 0
                        },
                        new
                        {
                            Id = "913C352577CE41C3BAF8A70F6F7DA2D0",
                            ImageUrl = "amazon.jpg",
                            IsSucceed = false,
                            Level = "Level 2",
                            Name = "Amazon",
                            Point = 0
                        },
                        new
                        {
                            Id = "B2899EED3BB24324B3FEDC69651BB4E9",
                            ImageUrl = "american-airlines.jpg",
                            IsSucceed = false,
                            Level = "Level 2",
                            Name = "American Airlines",
                            Point = 0
                        },
                        new
                        {
                            Id = "2DF8FEB1630840799BF10990475599B6",
                            ImageUrl = "apple.jpg",
                            IsSucceed = false,
                            Level = "Level 2",
                            Name = "Apple",
                            Point = 0
                        },
                        new
                        {
                            Id = "3D63BBA59E6046B9A9F5BB3C0B3BDF06",
                            ImageUrl = "ariel.jpg",
                            IsSucceed = false,
                            Level = "Level 2",
                            Name = "Ariel",
                            Point = 0
                        },
                        new
                        {
                            Id = "6CEF2D2A4D2245F1B53FFC2139122841",
                            ImageUrl = "bank-of-america.jpg",
                            IsSucceed = false,
                            Level = "Level 2",
                            Name = "Bank Of America",
                            Point = 0
                        },
                        new
                        {
                            Id = "E385777B335B4FFAA708BAE6AB05DDD8",
                            ImageUrl = "bbc.jpg",
                            IsSucceed = false,
                            Level = "Level 2",
                            Name = "BBC",
                            Point = 0
                        },
                        new
                        {
                            Id = "751520030B924A3C93D3369A46FD9CEC",
                            ImageUrl = "bluetooth.jpg",
                            IsSucceed = false,
                            Level = "Level 2",
                            Name = "Bluetooth",
                            Point = 0
                        },
                        new
                        {
                            Id = "B6AB5D8A1193416ABF6F360E40B51271",
                            ImageUrl = "burger-king.jpg",
                            IsSucceed = false,
                            Level = "Level 2",
                            Name = "Burger King",
                            Point = 0
                        },
                        new
                        {
                            Id = "34A037DEC7D54296AE479ED80B519BA4",
                            ImageUrl = "crocs.jpg",
                            IsSucceed = false,
                            Level = "Level 2",
                            Name = "Crocs",
                            Point = 0
                        },
                        new
                        {
                            Id = "F406307EC17A4284B2B7872EFB404788",
                            ImageUrl = "diesel.jpg",
                            IsSucceed = false,
                            Level = "Level 2",
                            Name = "Diesel",
                            Point = 0
                        },
                        new
                        {
                            Id = "EF30DF689154464C82E09DB69B91375F",
                            ImageUrl = "ghostbusters.jpg",
                            IsSucceed = false,
                            Level = "Level 2",
                            Name = "Ghostbusters",
                            Point = 0
                        },
                        new
                        {
                            Id = "7B1219E19BA0489991CCFFD814512EAD",
                            ImageUrl = "glaxosmithklein.jpg",
                            IsSucceed = false,
                            Level = "Level 2",
                            Name = "Glaxosmithklein",
                            Point = 0
                        },
                        new
                        {
                            Id = "CBAF3F2172FE4D878D6DC58862298033",
                            ImageUrl = "kodak.jpg",
                            IsSucceed = false,
                            Level = "Level 2",
                            Name = "Kodak",
                            Point = 0
                        },
                        new
                        {
                            Id = "408FBA834A8E42C8AE8D091D5C1763F1",
                            ImageUrl = "lacoste.jpg",
                            IsSucceed = false,
                            Level = "Level 2",
                            Name = "Lacoste",
                            Point = 0
                        },
                        new
                        {
                            Id = "DD56BC4470634F5782325F433DFD9482",
                            ImageUrl = "milka.jpg",
                            IsSucceed = false,
                            Level = "Level 2",
                            Name = "Milka",
                            Point = 0
                        },
                        new
                        {
                            Id = "D2CDD951B2F74C09AF7B4E3931E27E9E",
                            ImageUrl = "nickelodeon.jpg",
                            IsSucceed = false,
                            Level = "Level 2",
                            Name = "Nickelodeon",
                            Point = 0
                        },
                        new
                        {
                            Id = "A8A624FB51A647838B02EDEE6508FB31",
                            ImageUrl = "nike.jpg",
                            IsSucceed = false,
                            Level = "Level 2",
                            Name = "Nike",
                            Point = 0
                        },
                        new
                        {
                            Id = "B8DE549E3D284594A2820802355938B2",
                            ImageUrl = "penguin.jpg",
                            IsSucceed = false,
                            Level = "Level 3",
                            Name = "Penguin",
                            Point = 0
                        },
                        new
                        {
                            Id = "A751B3A7E9C642C3B03A64A4D72F1155",
                            ImageUrl = "pringles.jpg",
                            IsSucceed = false,
                            Level = "Level 3",
                            Name = "Pringles",
                            Point = 0
                        },
                        new
                        {
                            Id = "5FFEC23E022A4364922FED7FCBD0DAEA",
                            ImageUrl = "rolls-royce.jpg",
                            IsSucceed = false,
                            Level = "Level 3",
                            Name = "Rolls Royce",
                            Point = 0
                        },
                        new
                        {
                            Id = "B08A9608C0D0492394C47F2C36D4B6A6",
                            ImageUrl = "twitter.jpg",
                            IsSucceed = false,
                            Level = "Level 3",
                            Name = "Twitter",
                            Point = 0
                        },
                        new
                        {
                            Id = "424069B62B1F4EAA9BD880A0D70D0CCC",
                            ImageUrl = "goodyear.jpg",
                            IsSucceed = false,
                            Level = "Level 3",
                            Name = "Goodyear",
                            Point = 0
                        },
                        new
                        {
                            Id = "39D4D18CC1A84D2AB3AC665DA5D5CCC5",
                            ImageUrl = "harry-potter.jpg",
                            IsSucceed = false,
                            Level = "Level 3",
                            Name = "Harry Potter",
                            Point = 0
                        },
                        new
                        {
                            Id = "32EF804E68834148BCF4249F1CF00592",
                            ImageUrl = "hello-kitty.jpg",
                            IsSucceed = false,
                            Level = "Level 3",
                            Name = "Hello Kitty",
                            Point = 0
                        },
                        new
                        {
                            Id = "3C719475CCC54B3BBFF200A839F6060D",
                            ImageUrl = "hm.jpg",
                            IsSucceed = false,
                            Level = "Level 3",
                            Name = "HM",
                            Point = 0
                        },
                        new
                        {
                            Id = "EE5AFDDFE8074C9BA2489B8C7F225AFF",
                            ImageUrl = "honda.jpg",
                            IsSucceed = false,
                            Level = "Level 3",
                            Name = "Honda",
                            Point = 0
                        },
                        new
                        {
                            Id = "97C74E47016D4312B431D7EAB8B03EF0",
                            ImageUrl = "nikon.jpg",
                            IsSucceed = false,
                            Level = "Level 3",
                            Name = "Nikon",
                            Point = 0
                        },
                        new
                        {
                            Id = "C58D0432C94D4AD7A0A6FDEBD04658B2",
                            ImageUrl = "pixar.jpg",
                            IsSucceed = false,
                            Level = "Level 3",
                            Name = "Pixar",
                            Point = 0
                        },
                        new
                        {
                            Id = "51CAA0B3A9EA4C428CBCA1D77A62A010",
                            ImageUrl = "puma.jpg",
                            IsSucceed = false,
                            Level = "Level 3",
                            Name = "Puma",
                            Point = 0
                        },
                        new
                        {
                            Id = "270F7705D4ED468399DA609D9E8D966B",
                            ImageUrl = "renault.jpg",
                            IsSucceed = false,
                            Level = "Level 3",
                            Name = "Renault",
                            Point = 0
                        },
                        new
                        {
                            Id = "33290C8165D142EDBD01AD0736806914",
                            ImageUrl = "seat.jpg",
                            IsSucceed = false,
                            Level = "Level 3",
                            Name = "Seat",
                            Point = 0
                        },
                        new
                        {
                            Id = "72C2CABA60E045CD8DAED7E3CFF9B7C6",
                            ImageUrl = "seven-eleven.jpg",
                            IsSucceed = false,
                            Level = "Level 3",
                            Name = "Seven Eleven",
                            Point = 0
                        },
                        new
                        {
                            Id = "15366934C2274D24B06F3B1E932A1C2F",
                            ImageUrl = "tag-heuer.jpg",
                            IsSucceed = false,
                            Level = "Level 3",
                            Name = "Tag Heuer",
                            Point = 0
                        },
                        new
                        {
                            Id = "DAC6FB043E9343FBABB9642859430CD4",
                            ImageUrl = "woolmark.jpg",
                            IsSucceed = false,
                            Level = "Level 3",
                            Name = "Woolmark",
                            Point = 0
                        },
                        new
                        {
                            Id = "93A1BF352D6043798F7E8B16976F416F",
                            ImageUrl = "xbox.jpg",
                            IsSucceed = false,
                            Level = "Level 3",
                            Name = "Xbox",
                            Point = 0
                        },
                        new
                        {
                            Id = "F9EC769AEE1C4F0CAF73620FECEB1AB5",
                            ImageUrl = "xerox.jpg",
                            IsSucceed = false,
                            Level = "Level 3",
                            Name = "Xerox",
                            Point = 0
                        },
                        new
                        {
                            Id = "3EC33CBC6FA0485394D5BDDAD66F0ABD",
                            ImageUrl = "yellow-pages.jpg",
                            IsSucceed = false,
                            Level = "Level 3",
                            Name = "Yellow Pages",
                            Point = 0
                        },
                        new
                        {
                            Id = "76839100E92D4C6982C84A3555E3C873",
                            ImageUrl = "acdc.jpg",
                            IsSucceed = false,
                            Level = "Level 4",
                            Name = "ACDC",
                            Point = 0
                        },
                        new
                        {
                            Id = "B2573489F8C34CC6BF0EF3459443EC50",
                            ImageUrl = "benetton.jpg",
                            IsSucceed = false,
                            Level = "Level 4",
                            Name = "Benetton",
                            Point = 0
                        },
                        new
                        {
                            Id = "F0377051A890410F952655BDF743AD25",
                            ImageUrl = "budweiser.jpg",
                            IsSucceed = false,
                            Level = "Level 4",
                            Name = "Budweiser",
                            Point = 0
                        },
                        new
                        {
                            Id = "94401C4CEA504E1CAC657E11296ABDC0",
                            ImageUrl = "cartoon-network.jpg",
                            IsSucceed = false,
                            Level = "Level 4",
                            Name = "Cartoon Network",
                            Point = 0
                        },
                        new
                        {
                            Id = "7AE5852403B846ADBB69F4B4D3C8F9DD",
                            ImageUrl = "cheerios.jpg",
                            IsSucceed = false,
                            Level = "Level 4",
                            Name = "Cheerios",
                            Point = 0
                        },
                        new
                        {
                            Id = "69584144C4844708B98F0B4AD8770C73",
                            ImageUrl = "discovery.jpg",
                            IsSucceed = false,
                            Level = "Level 4",
                            Name = "Discovery",
                            Point = 0
                        },
                        new
                        {
                            Id = "68ACE31F3DC1498E88273B766CA6723C",
                            ImageUrl = "dove.jpg",
                            IsSucceed = false,
                            Level = "Level 4",
                            Name = "Dove",
                            Point = 0
                        },
                        new
                        {
                            Id = "A84ACACA328A4BBC9CED1F0A18CC4667",
                            ImageUrl = "durex.jpg",
                            IsSucceed = false,
                            Level = "Level 4",
                            Name = "Durex",
                            Point = 0
                        },
                        new
                        {
                            Id = "4550EB736F6F4AE28FB8EF15C4BF5602",
                            ImageUrl = "fisherprice.jpg",
                            IsSucceed = false,
                            Level = "Level 4",
                            Name = "Fisherprice",
                            Point = 0
                        },
                        new
                        {
                            Id = "101B229A2AC542E88338674E82B6CAD3",
                            ImageUrl = "fosters.jpg",
                            IsSucceed = false,
                            Level = "Level 4",
                            Name = "Fosters",
                            Point = 0
                        },
                        new
                        {
                            Id = "647734A85B0F467D95463457ECFD940E",
                            ImageUrl = "illy.jpg",
                            IsSucceed = false,
                            Level = "Level 4",
                            Name = "Illy",
                            Point = 0
                        },
                        new
                        {
                            Id = "A3D8F8F17C7A4B4AB562E09B3C687F23",
                            ImageUrl = "john-deere.jpg",
                            IsSucceed = false,
                            Level = "Level 4",
                            Name = "John Deere",
                            Point = 0
                        },
                        new
                        {
                            Id = "0AD6460B4583487F9DD9EB9207701841",
                            ImageUrl = "kia.jpg",
                            IsSucceed = false,
                            Level = "Level 4",
                            Name = "Kia",
                            Point = 0
                        },
                        new
                        {
                            Id = "491AED3B98E140079599352A783A4094",
                            ImageUrl = "kleenex.jpg",
                            IsSucceed = false,
                            Level = "Level 4",
                            Name = "Kleenex",
                            Point = 0
                        },
                        new
                        {
                            Id = "C258487CB3734DEAB96372DC420796E4",
                            ImageUrl = "kraft.jpg",
                            IsSucceed = false,
                            Level = "Level 4",
                            Name = "Kraft",
                            Point = 0
                        },
                        new
                        {
                            Id = "31C7A01918714CCBA30EF47F233BC11B",
                            ImageUrl = "land-rover.jpg",
                            IsSucceed = false,
                            Level = "Level 4",
                            Name = "Land Rover",
                            Point = 0
                        },
                        new
                        {
                            Id = "FDE39DAA70D14AA8BA27E9D2E9F18001",
                            ImageUrl = "linkedin.jpg",
                            IsSucceed = false,
                            Level = "Level 4",
                            Name = "Linkedin",
                            Point = 0
                        },
                        new
                        {
                            Id = "2521420EBBDD4227940374EE34B1B29E",
                            ImageUrl = "malibu.jpg",
                            IsSucceed = false,
                            Level = "Level 4",
                            Name = "Malibu",
                            Point = 0
                        },
                        new
                        {
                            Id = "6A5AAF28080D42438A8F3E22D7B15F04",
                            ImageUrl = "umbro.jpg",
                            IsSucceed = false,
                            Level = "Level 4",
                            Name = "Umbro",
                            Point = 0
                        },
                        new
                        {
                            Id = "D76EBF718CE74152AEBCB10731C79D3C",
                            ImageUrl = "wifi.jpg",
                            IsSucceed = false,
                            Level = "Level 4",
                            Name = "Wifi",
                            Point = 0
                        },
                        new
                        {
                            Id = "AC3ABC83D9D64DE89D49B896C39A7C4C",
                            ImageUrl = "air-jordan.jpg",
                            IsSucceed = false,
                            Level = "Level 5",
                            Name = "Air Jordan",
                            Point = 0
                        },
                        new
                        {
                            Id = "ACE28AF355714900B75DBEF544E55D66",
                            ImageUrl = "android.jpg",
                            IsSucceed = false,
                            Level = "Level 5",
                            Name = "Android",
                            Point = 0
                        },
                        new
                        {
                            Id = "D555E32A53894F55B89CA3B29F53883A",
                            ImageUrl = "asus.jpg",
                            IsSucceed = false,
                            Level = "Level 5",
                            Name = "Asus",
                            Point = 0
                        },
                        new
                        {
                            Id = "8FE65C80E4FA4BC9A47080F7E5D56BD1",
                            ImageUrl = "atari.jpg",
                            IsSucceed = false,
                            Level = "Level 5",
                            Name = "Atari",
                            Point = 0
                        },
                        new
                        {
                            Id = "E85B339692A1451F925455690D5D57E1",
                            ImageUrl = "avery.jpg",
                            IsSucceed = false,
                            Level = "Level 5",
                            Name = "Avery",
                            Point = 0
                        },
                        new
                        {
                            Id = "7FFDEFE9F5A04539B3FFA25BA24875F2",
                            ImageUrl = "chiquita.jpg",
                            IsSucceed = false,
                            Level = "Level 5",
                            Name = "Chiquita",
                            Point = 0
                        },
                        new
                        {
                            Id = "B64CC1A220984E4199652CCA721E856D",
                            ImageUrl = "chupa-chups.jpg",
                            IsSucceed = false,
                            Level = "Level 5",
                            Name = "Chupa Chups",
                            Point = 0
                        },
                        new
                        {
                            Id = "3EEDDC590A624433AE9D9605FBBD4CC0",
                            ImageUrl = "delta.jpg",
                            IsSucceed = false,
                            Level = "Level 5",
                            Name = "Delta",
                            Point = 0
                        },
                        new
                        {
                            Id = "C595350D0EB14CB9A1939533025F92A6",
                            ImageUrl = "fiat.jpg",
                            IsSucceed = false,
                            Level = "Level 5",
                            Name = "Fiat",
                            Point = 0
                        },
                        new
                        {
                            Id = "6B139578A16744FDA06AC2AC15456595",
                            ImageUrl = "fsc.jpg",
                            IsSucceed = false,
                            Level = "Level 5",
                            Name = "Fsc",
                            Point = 0
                        },
                        new
                        {
                            Id = "D3CA9A0586F541EC8B872C26D066F013",
                            ImageUrl = "lays.jpg",
                            IsSucceed = false,
                            Level = "Level 5",
                            Name = "Lays",
                            Point = 0
                        },
                        new
                        {
                            Id = "BE418D9742DF41408F68D7F7F686AEBB",
                            ImageUrl = "nespresso.jpg",
                            IsSucceed = false,
                            Level = "Level 5",
                            Name = "Nespresso",
                            Point = 0
                        },
                        new
                        {
                            Id = "C4B901949D09495A905B2826370106F4",
                            ImageUrl = "nestle.jpg",
                            IsSucceed = false,
                            Level = "Level 5",
                            Name = "Nestle",
                            Point = 0
                        },
                        new
                        {
                            Id = "5F318089425A4700ABD3E7AAD7D9755D",
                            ImageUrl = "nivea.jpg",
                            IsSucceed = false,
                            Level = "Level 5",
                            Name = "Nivea",
                            Point = 0
                        },
                        new
                        {
                            Id = "2CAE6AC58716446BA8E3B526D116B485",
                            ImageUrl = "pampers.jpg",
                            IsSucceed = false,
                            Level = "Level 5",
                            Name = "Pampers",
                            Point = 0
                        },
                        new
                        {
                            Id = "1978F9CF8C9B4F3AAE07139CBCAA39B4",
                            ImageUrl = "sheraton.jpg",
                            IsSucceed = false,
                            Level = "Level 5",
                            Name = "Sheraton",
                            Point = 0
                        },
                        new
                        {
                            Id = "8F61DBCB3A6D49B0B4A3D24565255E3A",
                            ImageUrl = "showtime.jpg",
                            IsSucceed = false,
                            Level = "Level 5",
                            Name = "Showtime",
                            Point = 0
                        },
                        new
                        {
                            Id = "530027BD6557484C8DDC59424F5AAE49",
                            ImageUrl = "target.jpg",
                            IsSucceed = false,
                            Level = "Level 5",
                            Name = "Target",
                            Point = 0
                        },
                        new
                        {
                            Id = "10AE4176C52D44058FAC41E06DE73CFE",
                            ImageUrl = "tictac.jpg",
                            IsSucceed = false,
                            Level = "Level 5",
                            Name = "Tictac",
                            Point = 0
                        },
                        new
                        {
                            Id = "CEE8D256987940568F7B4D8A79246158",
                            ImageUrl = "total.jpg",
                            IsSucceed = false,
                            Level = "Level 5",
                            Name = "Total",
                            Point = 0
                        },
                        new
                        {
                            Id = "8F5C577CBE2C48E4A8C00AD77DCDE31B",
                            ImageUrl = "bridgestone.jpg",
                            IsSucceed = false,
                            Level = "Level 6",
                            Name = "Bridgestone",
                            Point = 0
                        },
                        new
                        {
                            Id = "B1CFA916D1AB43B2A1207F94DB421F0B",
                            ImageUrl = "champion.jpg",
                            IsSucceed = false,
                            Level = "Level 6",
                            Name = "Champion",
                            Point = 0
                        },
                        new
                        {
                            Id = "41460B8D35B34C94823BA604BA6D7113",
                            ImageUrl = "compaq.jpg",
                            IsSucceed = false,
                            Level = "Level 6",
                            Name = "Compaq",
                            Point = 0
                        },
                        new
                        {
                            Id = "D9F83A455EAA4D8EA0D85FA4AEA53713",
                            ImageUrl = "corona.jpg",
                            IsSucceed = false,
                            Level = "Level 6",
                            Name = "Corona",
                            Point = 0
                        },
                        new
                        {
                            Id = "3A12165FF0DB4A2DB9E4E8F2BA958F81",
                            ImageUrl = "dreamworks.jpg",
                            IsSucceed = false,
                            Level = "Level 6",
                            Name = "Dreamworks",
                            Point = 0
                        },
                        new
                        {
                            Id = "B69A2D08AE0F43B98DF138E6BB5CCF79",
                            ImageUrl = "fishermans-friend.jpg",
                            IsSucceed = false,
                            Level = "Level 6",
                            Name = "Fishermans Friend",
                            Point = 0
                        },
                        new
                        {
                            Id = "1DD78E33FEA7487C93D54573506A828D",
                            ImageUrl = "fred-perry.jpg",
                            IsSucceed = false,
                            Level = "Level 6",
                            Name = "Fred Perry",
                            Point = 0
                        },
                        new
                        {
                            Id = "38AA297C012E4F87AAB9D0DF1E169F84",
                            ImageUrl = "girl-scouts-of-america.jpg",
                            IsSucceed = false,
                            Level = "Level 6",
                            Name = "Girl Scouts Of America",
                            Point = 0
                        },
                        new
                        {
                            Id = "ACCDB35DDB094945A3F05E6662BC61C9",
                            ImageUrl = "infiniti.jpg",
                            IsSucceed = false,
                            Level = "Level 6",
                            Name = "Infiniti",
                            Point = 0
                        },
                        new
                        {
                            Id = "036A3F29AFFA44A5801CF0D0094F3446",
                            ImageUrl = "maggi.jpg",
                            IsSucceed = false,
                            Level = "Level 6",
                            Name = "Maggi",
                            Point = 0
                        },
                        new
                        {
                            Id = "23DE09D2351D41B5899127A16CB5D989",
                            ImageUrl = "mastercard.jpg",
                            IsSucceed = false,
                            Level = "Level 6",
                            Name = "Mastercard",
                            Point = 0
                        },
                        new
                        {
                            Id = "47A42816D1DF4A3B8779AA9A985AFE63",
                            ImageUrl = "mozilla.jpg",
                            IsSucceed = false,
                            Level = "Level 6",
                            Name = "Mozilla",
                            Point = 0
                        },
                        new
                        {
                            Id = "F9D2443D9B584BB99C2E85503694B2BF",
                            ImageUrl = "oralb.jpg",
                            IsSucceed = false,
                            Level = "Level 6",
                            Name = "OralB",
                            Point = 0
                        },
                        new
                        {
                            Id = "948869D65D0B401CAE71FE672CC6F38F",
                            ImageUrl = "quicktime.jpg",
                            IsSucceed = false,
                            Level = "Level 6",
                            Name = "QuickTime",
                            Point = 0
                        },
                        new
                        {
                            Id = "6C8DC6E0522A44BC8CDBB1AE7FDF81B5",
                            ImageUrl = "roland-garros.jpg",
                            IsSucceed = false,
                            Level = "Level 6",
                            Name = "Roland Garros",
                            Point = 0
                        },
                        new
                        {
                            Id = "22C79AA344C9491D800F9204F35A8356",
                            ImageUrl = "spar.jpg",
                            IsSucceed = false,
                            Level = "Level 6",
                            Name = "Spar",
                            Point = 0
                        },
                        new
                        {
                            Id = "777D9DDE462D4DD8BC6413D1D863F181",
                            ImageUrl = "thai-airways.jpg",
                            IsSucceed = false,
                            Level = "Level 6",
                            Name = "Thai Airways",
                            Point = 0
                        },
                        new
                        {
                            Id = "D967A1130EC54CBB8B3B880438DE06FB",
                            ImageUrl = "tissot.jpg",
                            IsSucceed = false,
                            Level = "Level 6",
                            Name = "Tissot",
                            Point = 0
                        },
                        new
                        {
                            Id = "AD8F6AFA5DBC4600B9F9D73AAD716AE8",
                            ImageUrl = "usb.jpg",
                            IsSucceed = false,
                            Level = "Level 6",
                            Name = "USB",
                            Point = 0
                        },
                        new
                        {
                            Id = "045060BA1E9946909156F10E4112CBA6",
                            ImageUrl = "usps.jpg",
                            IsSucceed = false,
                            Level = "Level 6",
                            Name = "USPS",
                            Point = 0
                        },
                        new
                        {
                            Id = "41919E201D254D5F802B002E74FA4D94",
                            ImageUrl = "banana-boat.jpg",
                            IsSucceed = false,
                            Level = "Level 7",
                            Name = "Banana Boat",
                            Point = 0
                        },
                        new
                        {
                            Id = "5F17298E04F544BFBF8FA4E8BD35A2F2",
                            ImageUrl = "bertolli.jpg",
                            IsSucceed = false,
                            Level = "Level 7",
                            Name = "Bertolli",
                            Point = 0
                        },
                        new
                        {
                            Id = "63222E7923B8401BA59409A092254D0A",
                            ImageUrl = "danone.jpg",
                            IsSucceed = false,
                            Level = "Level 7",
                            Name = "Danone",
                            Point = 0
                        },
                        new
                        {
                            Id = "99485E0169F3485F96B803C694881B56",
                            ImageUrl = "total.jpg",
                            IsSucceed = false,
                            Level = "Level 7",
                            Name = "Total",
                            Point = 0
                        },
                        new
                        {
                            Id = "107C562D9EC3453BB150E52F720DE31C",
                            ImageUrl = "delonghi.jpg",
                            IsSucceed = false,
                            Level = "Level 7",
                            Name = "Delonghi",
                            Point = 0
                        },
                        new
                        {
                            Id = "DED111161BF34CB5818BC482F2AA1322",
                            ImageUrl = "dupont.jpg",
                            IsSucceed = false,
                            Level = "Level 7",
                            Name = "Dupont",
                            Point = 0
                        },
                        new
                        {
                            Id = "54B9573A71C84ACFA56AFBE5C2E8FC15",
                            ImageUrl = "emirates.jpg",
                            IsSucceed = false,
                            Level = "Level 7",
                            Name = "Emirates",
                            Point = 0
                        },
                        new
                        {
                            Id = "FF301A945D6D4ED489E5043C020A5AF8",
                            ImageUrl = "nasa.jpg",
                            IsSucceed = false,
                            Level = "Level 7",
                            Name = "NASA",
                            Point = 0
                        },
                        new
                        {
                            Id = "7043ED5584F041F9B2DBDE1D74C5583A",
                            ImageUrl = "oxfam.jpg",
                            IsSucceed = false,
                            Level = "Level 7",
                            Name = "Oxfam",
                            Point = 0
                        },
                        new
                        {
                            Id = "FEF158FCC63242B19184C20A5A25172B",
                            ImageUrl = "panam.jpg",
                            IsSucceed = false,
                            Level = "Level 7",
                            Name = "Panam",
                            Point = 0
                        },
                        new
                        {
                            Id = "F88FBB305F5847209DAA04ED2D2719FD",
                            ImageUrl = "parker.jpg",
                            IsSucceed = false,
                            Level = "Level 7",
                            Name = "Parker",
                            Point = 0
                        },
                        new
                        {
                            Id = "706F8C3C002749C6A80E52706E2F91A4",
                            ImageUrl = "parker-brothers.jpg",
                            IsSucceed = false,
                            Level = "Level 7",
                            Name = "Parker Brothers",
                            Point = 0
                        },
                        new
                        {
                            Id = "D46608970C6D47199701A2598DA42FC5",
                            ImageUrl = "paul-and-shark.jpg",
                            IsSucceed = false,
                            Level = "Level 7",
                            Name = "Paul And Shark",
                            Point = 0
                        },
                        new
                        {
                            Id = "6D892B7306834A2A809DFCA0C16C60E3",
                            ImageUrl = "pfizer.jpg",
                            IsSucceed = false,
                            Level = "Level 7",
                            Name = "Pfizer",
                            Point = 0
                        },
                        new
                        {
                            Id = "87C13488BE204FB29CBE1FEB550EC315",
                            ImageUrl = "piaggio.jpg",
                            IsSucceed = false,
                            Level = "Level 7",
                            Name = "Piaggio",
                            Point = 0
                        },
                        new
                        {
                            Id = "368EAE7D8BE14B80A25063A7B9D30098",
                            ImageUrl = "rss.jpg",
                            IsSucceed = false,
                            Level = "Level 7",
                            Name = "RSS",
                            Point = 0
                        },
                        new
                        {
                            Id = "B54B827D5C204ABF92F83A1F08C49FB9",
                            ImageUrl = "snapple.jpg",
                            IsSucceed = false,
                            Level = "Level 7",
                            Name = "Snapple",
                            Point = 0
                        },
                        new
                        {
                            Id = "3C4782CF86334A7891602A5D2B0BE050",
                            ImageUrl = "stabilo.jpg",
                            IsSucceed = false,
                            Level = "Level 7",
                            Name = "Stabilo",
                            Point = 0
                        },
                        new
                        {
                            Id = "3687AEEBA43443FD9CFB064424F562DF",
                            ImageUrl = "the-north-face.jpg",
                            IsSucceed = false,
                            Level = "Level 7",
                            Name = "The North Face",
                            Point = 0
                        },
                        new
                        {
                            Id = "91AFCFADC6DE4F68941B742D74FE4719",
                            ImageUrl = "tomtom.jpg",
                            IsSucceed = false,
                            Level = "Level 7",
                            Name = "Tomtom",
                            Point = 0
                        },
                        new
                        {
                            Id = "E78EC76783DA4E5682604A619A1A50B2",
                            ImageUrl = "unicef.jpg",
                            IsSucceed = false,
                            Level = "Level 7",
                            Name = "Unicef",
                            Point = 0
                        },
                        new
                        {
                            Id = "1A1801A01E594B4EAEA3FCDDAD6825CB",
                            ImageUrl = "bugatti.jpg",
                            IsSucceed = false,
                            Level = "Level 8",
                            Name = "Bugatti",
                            Point = 0
                        },
                        new
                        {
                            Id = "021A808A25354BBB835086EF40EA4907",
                            ImageUrl = "cat.jpg",
                            IsSucceed = false,
                            Level = "Level 8",
                            Name = "Cat",
                            Point = 0
                        },
                        new
                        {
                            Id = "A0044FE0E1C548889936370E1BFE46CE",
                            ImageUrl = "enron.jpg",
                            IsSucceed = false,
                            Level = "Level 8",
                            Name = "Enron",
                            Point = 0
                        },
                        new
                        {
                            Id = "CC2581F716C14BBCB232DDA1AA54031B",
                            ImageUrl = "estee-lauder.jpg",
                            IsSucceed = false,
                            Level = "Level 8",
                            Name = "Estee Lauder",
                            Point = 0
                        },
                        new
                        {
                            Id = "0BD4227830004EB7A82D48E88CC4986A",
                            ImageUrl = "eurosport.jpg",
                            IsSucceed = false,
                            Level = "Level 8",
                            Name = "EuroSport",
                            Point = 0
                        },
                        new
                        {
                            Id = "F6654309B46747DF9E6B02C1B1E9A271",
                            ImageUrl = "exxon.jpg",
                            IsSucceed = false,
                            Level = "Level 8",
                            Name = "Exxon",
                            Point = 0
                        },
                        new
                        {
                            Id = "26B6696AA8F44E8F98A0550A73932326",
                            ImageUrl = "fender.jpg",
                            IsSucceed = false,
                            Level = "Level 8",
                            Name = "Fender",
                            Point = 0
                        },
                        new
                        {
                            Id = "94D6E35E9DA041219E15017F2C7C114F",
                            ImageUrl = "fendi.jpg",
                            IsSucceed = false,
                            Level = "Level 8",
                            Name = "Fendi",
                            Point = 0
                        },
                        new
                        {
                            Id = "3C05E67714204636AE80954CD14D59D0",
                            ImageUrl = "firebird.jpg",
                            IsSucceed = false,
                            Level = "Level 8",
                            Name = "Firebird",
                            Point = 0
                        },
                        new
                        {
                            Id = "2FD16C1984B743F687B34F9D649C03DE",
                            ImageUrl = "firestone.jpg",
                            IsSucceed = false,
                            Level = "Level 8",
                            Name = "Firestone",
                            Point = 0
                        },
                        new
                        {
                            Id = "181FB3A129B14DF7B54A8A0F98163D90",
                            ImageUrl = "fruit-of-the-loom.jpg",
                            IsSucceed = false,
                            Level = "Level 8",
                            Name = "Fruit Of The Loom",
                            Point = 0
                        },
                        new
                        {
                            Id = "ADBC1D7BED324E34B0F4C30AD4291A08",
                            ImageUrl = "fujitsu.jpg",
                            IsSucceed = false,
                            Level = "Level 8",
                            Name = "Fujitsu",
                            Point = 0
                        },
                        new
                        {
                            Id = "6D93596AB3164217B7A1656B423761CC",
                            ImageUrl = "gatorade.jpg",
                            IsSucceed = false,
                            Level = "Level 8",
                            Name = "Gatorade",
                            Point = 0
                        },
                        new
                        {
                            Id = "F78ADD863B324D3596B6A34230AF2C10",
                            ImageUrl = "hot-wheels.jpg",
                            IsSucceed = false,
                            Level = "Level 8",
                            Name = "Hot Wheels",
                            Point = 0
                        },
                        new
                        {
                            Id = "C3279669A6034477A30CC1FCA3125E79",
                            ImageUrl = "hsbc.jpg",
                            IsSucceed = false,
                            Level = "Level 8",
                            Name = "Hsbc",
                            Point = 0
                        },
                        new
                        {
                            Id = "6C154A64973D473898259971C943FB5C",
                            ImageUrl = "kenwood.jpg",
                            IsSucceed = false,
                            Level = "Level 8",
                            Name = "Kenwood",
                            Point = 0
                        },
                        new
                        {
                            Id = "30F8FFC519DC4F6EA4339D2008D59817",
                            ImageUrl = "linkin-park.jpg",
                            IsSucceed = false,
                            Level = "Level 8",
                            Name = "Linkin Park",
                            Point = 0
                        },
                        new
                        {
                            Id = "4A44531B3CA543059EA40731F2842A9C",
                            ImageUrl = "logitech.jpg",
                            IsSucceed = false,
                            Level = "Level 8",
                            Name = "Logitech",
                            Point = 0
                        },
                        new
                        {
                            Id = "9F896FE68F8C4A47863202C3847F3748",
                            ImageUrl = "lufthansa.jpg",
                            IsSucceed = false,
                            Level = "Level 8",
                            Name = "Lufthansa",
                            Point = 0
                        },
                        new
                        {
                            Id = "9CA972F8F20B4ED5A1FAFA0EC580FE20",
                            ImageUrl = "mont-blanc.jpg",
                            IsSucceed = false,
                            Level = "Level 8",
                            Name = "Mont Blanc",
                            Point = 0
                        },
                        new
                        {
                            Id = "85B655360D014A19AE51E3F9FEED725C",
                            ImageUrl = "akzo-nobel.jpg",
                            IsSucceed = false,
                            Level = "Level 9",
                            Name = "Akzo Nobel",
                            Point = 0
                        },
                        new
                        {
                            Id = "F6F07C9688C74585A45D8762922D918C",
                            ImageUrl = "allianz.jpg",
                            IsSucceed = false,
                            Level = "Level 9",
                            Name = "Allianz",
                            Point = 0
                        },
                        new
                        {
                            Id = "F7E6EAE956A442AA95E00A21F5CB5436",
                            ImageUrl = "asics.jpg",
                            IsSucceed = false,
                            Level = "Level 9",
                            Name = "Asics",
                            Point = 0
                        },
                        new
                        {
                            Id = "E864F7C45A084D0BAFE770771960A200",
                            ImageUrl = "bad-religion.jpg",
                            IsSucceed = false,
                            Level = "Level 9",
                            Name = "Bad Religion",
                            Point = 0
                        },
                        new
                        {
                            Id = "299E3A0E82B84231BD4E97A589BE6D76",
                            ImageUrl = "bat.jpg",
                            IsSucceed = false,
                            Level = "Level 9",
                            Name = "Bat",
                            Point = 0
                        },
                        new
                        {
                            Id = "CE0A998507AA4AF2827743010283D344",
                            ImageUrl = "billabong.jpg",
                            IsSucceed = false,
                            Level = "Level 9",
                            Name = "Billabong",
                            Point = 0
                        },
                        new
                        {
                            Id = "D041980F6AA841EFA27D77443B16B964",
                            ImageUrl = "metallica.jpg",
                            IsSucceed = false,
                            Level = "Level 9",
                            Name = "Metallica",
                            Point = 0
                        },
                        new
                        {
                            Id = "DCC3409093FB45C2AF02F6D0615EBB64",
                            ImageUrl = "minecraft.jpg",
                            IsSucceed = false,
                            Level = "Level 9",
                            Name = "Minecraft",
                            Point = 0
                        },
                        new
                        {
                            Id = "063D63EE5DB647909E3953B9F89E1E29",
                            ImageUrl = "nandos.jpg",
                            IsSucceed = false,
                            Level = "Level 9",
                            Name = "Nandos",
                            Point = 0
                        },
                        new
                        {
                            Id = "4B202AC354E540ACAED752CEE949BCCF",
                            ImageUrl = "novartis.jpg",
                            IsSucceed = false,
                            Level = "Level 9",
                            Name = "Novartis",
                            Point = 0
                        },
                        new
                        {
                            Id = "E7956279F3654C4994B019C8A517E874",
                            ImageUrl = "pearl-jam.jpg",
                            IsSucceed = false,
                            Level = "Level 9",
                            Name = "Pearl Jam",
                            Point = 0
                        },
                        new
                        {
                            Id = "D5BF5B6F7A654A74B7D1AE027093281C",
                            ImageUrl = "quaker-oats.jpg",
                            IsSucceed = false,
                            Level = "Level 9",
                            Name = "Quaker Oats",
                            Point = 0
                        },
                        new
                        {
                            Id = "2C34082DCF6746BD9103EA2125F67DB1",
                            ImageUrl = "sanyo.jpg",
                            IsSucceed = false,
                            Level = "Level 9",
                            Name = "Sanyo",
                            Point = 0
                        },
                        new
                        {
                            Id = "32FB28D7B80147CEBA226E3635FEE5BA",
                            ImageUrl = "Subaru.jpg",
                            IsSucceed = false,
                            Level = "Level 9",
                            Name = "Subaru",
                            Point = 0
                        },
                        new
                        {
                            Id = "668D45AF827045DA81790D708AAA4E28",
                            ImageUrl = "suzuki.jpg",
                            IsSucceed = false,
                            Level = "Level 9",
                            Name = "Suzuki",
                            Point = 0
                        },
                        new
                        {
                            Id = "D074EF3CDD434FC8A77809232069C03C",
                            ImageUrl = "tdk.jpg",
                            IsSucceed = false,
                            Level = "Level 9",
                            Name = "Tdk",
                            Point = 0
                        },
                        new
                        {
                            Id = "B9E66F1BE24B4C9A810AD56002B4DBA2",
                            ImageUrl = "topgun.jpg",
                            IsSucceed = false,
                            Level = "Level 9",
                            Name = "TopGun",
                            Point = 0
                        },
                        new
                        {
                            Id = "C0298D189AD14A9997FFE522EAAA5E7C",
                            ImageUrl = "uefa.jpg",
                            IsSucceed = false,
                            Level = "Level 9",
                            Name = "UEFA",
                            Point = 0
                        },
                        new
                        {
                            Id = "067FCB89B29E44DEB46833643DC6344D",
                            ImageUrl = "whirlpool.jpg",
                            IsSucceed = false,
                            Level = "Level 9",
                            Name = "Whirlpool",
                            Point = 0
                        },
                        new
                        {
                            Id = "1C9B25CC1D8F4633ACD83806ABF47BBA",
                            ImageUrl = "wilson.jpg",
                            IsSucceed = false,
                            Level = "Level 9",
                            Name = "Wilson",
                            Point = 0
                        },
                        new
                        {
                            Id = "F97CC77D6B284051B6E34F4D83E26CBB",
                            ImageUrl = "burton.jpg",
                            IsSucceed = false,
                            Level = "Level 10",
                            Name = "Burton",
                            Point = 0
                        },
                        new
                        {
                            Id = "8A907B2D310848D2830F5C60C381CBFF",
                            ImageUrl = "capcom.jpg",
                            IsSucceed = false,
                            Level = "Level 10",
                            Name = "Capcom",
                            Point = 0
                        },
                        new
                        {
                            Id = "4661163756F14EA4ADC267DFF9FC3BDB",
                            ImageUrl = "dole.jpg",
                            IsSucceed = false,
                            Level = "Level 10",
                            Name = "Dole",
                            Point = 0
                        },
                        new
                        {
                            Id = "814B35BA3328420DA761E0E92231CF35",
                            ImageUrl = "erricson.jpg",
                            IsSucceed = false,
                            Level = "Level 10",
                            Name = "Erricson",
                            Point = 0
                        },
                        new
                        {
                            Id = "7BE834D43A2943349E6EAA40C654CB91",
                            ImageUrl = "huawei.jpg",
                            IsSucceed = false,
                            Level = "Level 10",
                            Name = "Huawei",
                            Point = 0
                        },
                        new
                        {
                            Id = "4FE52184F1EC406D90A25EF05CC425FC",
                            ImageUrl = "icq.jpg",
                            IsSucceed = false,
                            Level = "Level 10",
                            Name = "Icq",
                            Point = 0
                        },
                        new
                        {
                            Id = "909DA9BB8C834AEC91A98138BC2BEF19",
                            ImageUrl = "kyocera.jpg",
                            IsSucceed = false,
                            Level = "Level 10",
                            Name = "Kyocera",
                            Point = 0
                        },
                        new
                        {
                            Id = "CBB50C2C5E5540FEA31B3CD7A36A0C38",
                            ImageUrl = "lancome.jpg",
                            IsSucceed = false,
                            Level = "Level 10",
                            Name = "Lancome",
                            Point = 0
                        },
                        new
                        {
                            Id = "24263CCD5D994F0E91DD24EEA495D7B2",
                            ImageUrl = "lotto.jpg",
                            IsSucceed = false,
                            Level = "Level 10",
                            Name = "Lotto",
                            Point = 0
                        },
                        new
                        {
                            Id = "1195E0D63BB5407997CA804AD77EC533",
                            ImageUrl = "lucent.jpg",
                            IsSucceed = false,
                            Level = "Level 10",
                            Name = "Lucent",
                            Point = 0
                        },
                        new
                        {
                            Id = "A144E48B473244A38856ED18F92D4415",
                            ImageUrl = "massey-ferguson.jpg",
                            IsSucceed = false,
                            Level = "Level 10",
                            Name = "Massey Ferguson",
                            Point = 0
                        },
                        new
                        {
                            Id = "0B7E05B026D245C5B5BC16CD9F2F69FE",
                            ImageUrl = "ncr.jpg",
                            IsSucceed = false,
                            Level = "Level 10",
                            Name = "Ncr",
                            Point = 0
                        },
                        new
                        {
                            Id = "9E00E3198B4B4CA89DE2A067BB253805",
                            ImageUrl = "nortel.jpg",
                            IsSucceed = false,
                            Level = "Level 10",
                            Name = "Nortel",
                            Point = 0
                        },
                        new
                        {
                            Id = "45D10F08072A4DBA84DFBA5AA1F705EF",
                            ImageUrl = "nvidia.jpg",
                            IsSucceed = false,
                            Level = "Level 10",
                            Name = "Nvidia",
                            Point = 0
                        },
                        new
                        {
                            Id = "A9BE592A26EB4DD0BCA55E1918A5369D",
                            ImageUrl = "pelikan.jpg",
                            IsSucceed = false,
                            Level = "Level 10",
                            Name = "Pelikan",
                            Point = 0
                        },
                        new
                        {
                            Id = "4DB859C6EDEE4E27AAECE3DCC7B21C65",
                            ImageUrl = "sap.jpg",
                            IsSucceed = false,
                            Level = "Level 10",
                            Name = "SAP",
                            Point = 0
                        },
                        new
                        {
                            Id = "22EFCD61B0E84E4E8CABD9019F782A62",
                            ImageUrl = "tata.jpg",
                            IsSucceed = false,
                            Level = "Level 10",
                            Name = "Tata",
                            Point = 0
                        },
                        new
                        {
                            Id = "47A42E57BAB747A4895FBA90B85F6B7A",
                            ImageUrl = "texas-instruments.jpg",
                            IsSucceed = false,
                            Level = "Level 10",
                            Name = "Texas Instruments",
                            Point = 0
                        },
                        new
                        {
                            Id = "84A0CBF14155441089C1AB35BC7CD39F",
                            ImageUrl = "the-ramones.jpg",
                            IsSucceed = false,
                            Level = "Level 10",
                            Name = "The Ramones",
                            Point = 0
                        },
                        new
                        {
                            Id = "44AC081B22B948BFBA5F2D20D6E8479F",
                            ImageUrl = "wwe.jpg",
                            IsSucceed = false,
                            Level = "Level 10",
                            Name = "WWE",
                            Point = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
