// <auto-generated />
using LogoQuiz.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LogoQuiz.Migrations
{
    [DbContext(typeof(Repository))]
    partial class RepositoryModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("LogoQuiz.Models.Logo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hint")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSucceed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Level")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Point")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Logos");

                    b.HasData(
                        new
                        {
                            Id = "423F5CDA2F2F408A91E9D8863D493226",
                            Hint = "***",
                            ImageUrl = "barbie.jpg",
                            IsSucceed = false,
                            Level = "Level 1",
                            Name = "Barbie",
                            Point = 0
                        },
                        new
                        {
                            Id = "65E0F3A493544DEA96E22B5D9BC2FF1A",
                            Hint = "***",
                            ImageUrl = "baskin-robbins.jpg",
                            IsSucceed = false,
                            Level = "Level 1",
                            Name = "Baskin Robbins",
                            Point = 0
                        },
                        new
                        {
                            Id = "EA01929A30F14C0DB59D34226976FF8A",
                            Hint = "***",
                            ImageUrl = "budget.jpg",
                            IsSucceed = false,
                            Level = "Level 1",
                            Name = "Budget",
                            Point = 0
                        },
                        new
                        {
                            Id = "A02B76FC43504C4688587E6310223DD4",
                            Hint = "***",
                            ImageUrl = "carlsberg.jpg",
                            IsSucceed = false,
                            Level = "Level 1",
                            Name = "Carlsberg",
                            Point = 0
                        },
                        new
                        {
                            Id = "003A422112684B03A5A08362E9BD8765",
                            Hint = "***",
                            ImageUrl = "dunkin-donuts.jpg",
                            IsSucceed = false,
                            Level = "Level 1",
                            Name = "Dunkin Donuts",
                            Point = 0
                        },
                        new
                        {
                            Id = "BC47FF53F3B54E3385D8FEC4EF3B679E",
                            Hint = "***",
                            ImageUrl = "facebook.jpg",
                            IsSucceed = false,
                            Level = "Level 1",
                            Name = "Facebook",
                            Point = 0
                        },
                        new
                        {
                            Id = "BDEB213702E64636814E1E1F36ED9A43",
                            Hint = "***",
                            ImageUrl = "fedex.jpg",
                            IsSucceed = false,
                            Level = "Level 1",
                            Name = "Fedex",
                            Point = 0
                        },
                        new
                        {
                            Id = "B66787EE43164CC1B27524470233AD33",
                            Hint = "***",
                            ImageUrl = "holiday-inn.jpg",
                            IsSucceed = false,
                            Level = "Level 1",
                            Name = "Holiday-inn",
                            Point = 0
                        },
                        new
                        {
                            Id = "3CC3522FBA564AA197BF0F9AFD2F629D",
                            Hint = "***",
                            ImageUrl = "jaguar.jpg",
                            IsSucceed = false,
                            Level = "Level 1",
                            Name = "Jaguar",
                            Point = 0
                        },
                        new
                        {
                            Id = "C7BF4DA2007349B6A423F78ECB47FD86",
                            Hint = "***",
                            ImageUrl = "kfc.jpg",
                            IsSucceed = false,
                            Level = "Level 1",
                            Name = "Kfc",
                            Point = 0
                        },
                        new
                        {
                            Id = "E84BF526DF6B42A98EEC854EF9261F8E",
                            Hint = "***",
                            ImageUrl = "knorr.jpg",
                            IsSucceed = false,
                            Level = "Level 1",
                            Name = "Knorr",
                            Point = 0
                        },
                        new
                        {
                            Id = "C208578F528F4A2F954274CC32C5A93D",
                            Hint = "***",
                            ImageUrl = "lexus.jpg",
                            IsSucceed = false,
                            Level = "Level 1",
                            Name = "Lexus",
                            Point = 0
                        },
                        new
                        {
                            Id = "CAA05AC083BA4D6AA24573D25959B6F3",
                            Hint = "***",
                            ImageUrl = "mcdonalds.jpg",
                            IsSucceed = false,
                            Level = "Level 1",
                            Name = "McDonalds",
                            Point = 0
                        },
                        new
                        {
                            Id = "74CB906E01224B0B8B2D671690C5E47E",
                            Hint = "***",
                            ImageUrl = "pepsi.jpg",
                            IsSucceed = false,
                            Level = "Level 1",
                            Name = "Pepsi",
                            Point = 0
                        },
                        new
                        {
                            Id = "8B9432BBCA3F46D5A3FB5F6915618F63",
                            Hint = "***",
                            ImageUrl = "playboy.jpg",
                            IsSucceed = false,
                            Level = "Level 1",
                            Name = "Playboy",
                            Point = 0
                        },
                        new
                        {
                            Id = "728AEAA382ED4765A062EA2CCA6CD955",
                            Hint = "***",
                            ImageUrl = "playstation.jpg",
                            IsSucceed = false,
                            Level = "Level 1",
                            Name = "PlayStation",
                            Point = 0
                        },
                        new
                        {
                            Id = "354BD9280B334E2697F66D94FAEDD689",
                            Hint = "***",
                            ImageUrl = "safeway.jpg",
                            IsSucceed = false,
                            Level = "Level 1",
                            Name = "Safeway",
                            Point = 0
                        },
                        new
                        {
                            Id = "92D8CD24EDB34A7CB6CB62127742C539",
                            Hint = "***",
                            ImageUrl = "the-body-shop.jpg",
                            IsSucceed = false,
                            Level = "Level 1",
                            Name = "The Body Shop",
                            Point = 0
                        },
                        new
                        {
                            Id = "8B05739E8B4944699F3FF07814A31477",
                            Hint = "***",
                            ImageUrl = "visa.jpg",
                            IsSucceed = false,
                            Level = "Level 1",
                            Name = "Visa",
                            Point = 0
                        },
                        new
                        {
                            Id = "428D3A53434C4C8C9B9DEAACAD0529E9",
                            Hint = "***",
                            ImageUrl = "yahoo.jpg",
                            IsSucceed = false,
                            Level = "Level 1",
                            Name = "Yahoo",
                            Point = 0
                        },
                        new
                        {
                            Id = "BC3D0428054F400FBBBCF4552B0897B1",
                            Hint = "***",
                            ImageUrl = "20th-century-fox.jpg",
                            IsSucceed = false,
                            Level = "Level 2",
                            Name = "20th Century Fox",
                            Point = 0
                        },
                        new
                        {
                            Id = "D069CFBB445C439E80ACB63AECBF2EC2",
                            Hint = "***",
                            ImageUrl = "absolut.jpg",
                            IsSucceed = false,
                            Level = "Level 2",
                            Name = "Absolut",
                            Point = 0
                        },
                        new
                        {
                            Id = "3FFAB14DBF38407A9905CA85E74E0D48",
                            Hint = "***",
                            ImageUrl = "adidas.jpg",
                            IsSucceed = false,
                            Level = "Level 2",
                            Name = "Adidas",
                            Point = 0
                        },
                        new
                        {
                            Id = "502DE760BDDA47ADABA958CD99464326",
                            Hint = "***",
                            ImageUrl = "amazon.jpg",
                            IsSucceed = false,
                            Level = "Level 2",
                            Name = "Amazon",
                            Point = 0
                        },
                        new
                        {
                            Id = "84CBE51ED2684C5FB6B5CB11986E6896",
                            Hint = "***",
                            ImageUrl = "american-airlines.jpg",
                            IsSucceed = false,
                            Level = "Level 2",
                            Name = "American Airlines",
                            Point = 0
                        },
                        new
                        {
                            Id = "B180B34D0FAE49A0BD96F15F455E80EA",
                            Hint = "***",
                            ImageUrl = "apple.jpg",
                            IsSucceed = false,
                            Level = "Level 2",
                            Name = "Apple",
                            Point = 0
                        },
                        new
                        {
                            Id = "121958E0637C49A688561DA5D9E29F0B",
                            Hint = "***",
                            ImageUrl = "ariel.jpg",
                            IsSucceed = false,
                            Level = "Level 2",
                            Name = "Ariel",
                            Point = 0
                        },
                        new
                        {
                            Id = "AD9F673A2D1F4E35A98C5EC1D9250F8F",
                            Hint = "***",
                            ImageUrl = "bank-of-america.jpg",
                            IsSucceed = false,
                            Level = "Level 2",
                            Name = "Bank Of America",
                            Point = 0
                        },
                        new
                        {
                            Id = "FBD96D8B17CC4AB88E0E289CDA1ADB3A",
                            Hint = "***",
                            ImageUrl = "bbc.jpg",
                            IsSucceed = false,
                            Level = "Level 2",
                            Name = "BBC",
                            Point = 0
                        },
                        new
                        {
                            Id = "17D45B3F9E1B44938A2052E79BFE64F7",
                            Hint = "***",
                            ImageUrl = "bluetooth.jpg",
                            IsSucceed = false,
                            Level = "Level 2",
                            Name = "Bluetooth",
                            Point = 0
                        },
                        new
                        {
                            Id = "064CCA0F843642508DD761577726A9DD",
                            Hint = "***",
                            ImageUrl = "burger-king.jpg",
                            IsSucceed = false,
                            Level = "Level 2",
                            Name = "Burger King",
                            Point = 0
                        },
                        new
                        {
                            Id = "9E0D5608835442A281293C516A9CFECE",
                            Hint = "***",
                            ImageUrl = "crocs.jpg",
                            IsSucceed = false,
                            Level = "Level 2",
                            Name = "Crocs",
                            Point = 0
                        },
                        new
                        {
                            Id = "BEA91DB628674FB1A4702D49303EC0C6",
                            Hint = "***",
                            ImageUrl = "diesel.jpg",
                            IsSucceed = false,
                            Level = "Level 2",
                            Name = "Diesel",
                            Point = 0
                        },
                        new
                        {
                            Id = "853373A74DDF40BD9200C97E54DB89E0",
                            Hint = "***",
                            ImageUrl = "ghostbusters.jpg",
                            IsSucceed = false,
                            Level = "Level 2",
                            Name = "Ghostbusters",
                            Point = 0
                        },
                        new
                        {
                            Id = "9AABEF3DABED481293C55A66F6F93099",
                            Hint = "***",
                            ImageUrl = "glaxosmithklein.jpg",
                            IsSucceed = false,
                            Level = "Level 2",
                            Name = "Glaxosmithklein",
                            Point = 0
                        },
                        new
                        {
                            Id = "391AE3FE86FC4CA48123BD7A19872F18",
                            Hint = "***",
                            ImageUrl = "kodak.jpg",
                            IsSucceed = false,
                            Level = "Level 2",
                            Name = "Kodak",
                            Point = 0
                        },
                        new
                        {
                            Id = "23BC0F99906B4E7AA4FC7188C13CD713",
                            Hint = "***",
                            ImageUrl = "lacoste.jpg",
                            IsSucceed = false,
                            Level = "Level 2",
                            Name = "Lacoste",
                            Point = 0
                        },
                        new
                        {
                            Id = "8D4C551D5A4E4045B07B7960449C9BE6",
                            Hint = "***",
                            ImageUrl = "milka.jpg",
                            IsSucceed = false,
                            Level = "Level 2",
                            Name = "Milka",
                            Point = 0
                        },
                        new
                        {
                            Id = "EA9DA6FD6ECA4486BA70AA439D8E07BB",
                            Hint = "***",
                            ImageUrl = "nickelodeon.jpg",
                            IsSucceed = false,
                            Level = "Level 2",
                            Name = "Nickelodeon",
                            Point = 0
                        },
                        new
                        {
                            Id = "A26DCFECEFBE40FD9C7C17040BB0A35C",
                            Hint = "***",
                            ImageUrl = "nike.jpg",
                            IsSucceed = false,
                            Level = "Level 2",
                            Name = "Nike",
                            Point = 0
                        },
                        new
                        {
                            Id = "79717D99BD934DF789C50B730D0C71BF",
                            Hint = "***",
                            ImageUrl = "penguin.jpg",
                            IsSucceed = false,
                            Level = "Level 3",
                            Name = "Penguin",
                            Point = 0
                        },
                        new
                        {
                            Id = "BDCD29C9CFD1456C88DAB82258C5712B",
                            Hint = "***",
                            ImageUrl = "pringles.jpg",
                            IsSucceed = false,
                            Level = "Level 3",
                            Name = "Pringles",
                            Point = 0
                        },
                        new
                        {
                            Id = "0A6CB91D08CD49038B7FA1A2CD372206",
                            Hint = "***",
                            ImageUrl = "rolls-royce.jpg",
                            IsSucceed = false,
                            Level = "Level 3",
                            Name = "Rolls Royce",
                            Point = 0
                        },
                        new
                        {
                            Id = "EF2BD46B750E4CF88958A46EF7E270A9",
                            Hint = "***",
                            ImageUrl = "twitter.jpg",
                            IsSucceed = false,
                            Level = "Level 3",
                            Name = "Twitter",
                            Point = 0
                        },
                        new
                        {
                            Id = "4741704A0889428D8065D2D347C07D84",
                            Hint = "***",
                            ImageUrl = "goodyear.jpg",
                            IsSucceed = false,
                            Level = "Level 3",
                            Name = "Goodyear",
                            Point = 0
                        },
                        new
                        {
                            Id = "ED7A0BF2CF544C5E8225A67DE14E4587",
                            Hint = "***",
                            ImageUrl = "harry-potter.jpg",
                            IsSucceed = false,
                            Level = "Level 3",
                            Name = "Harry Potter",
                            Point = 0
                        },
                        new
                        {
                            Id = "A88E32EA02384164A6D444D11B9DC15D",
                            Hint = "***",
                            ImageUrl = "hello-kitty.jpg",
                            IsSucceed = false,
                            Level = "Level 3",
                            Name = "Hello Kitty",
                            Point = 0
                        },
                        new
                        {
                            Id = "6CBD026238694E7EBCEF0B92E181972B",
                            Hint = "***",
                            ImageUrl = "hm.jpg",
                            IsSucceed = false,
                            Level = "Level 3",
                            Name = "HM",
                            Point = 0
                        },
                        new
                        {
                            Id = "F721268FEBBE4F78A631698DEF388313",
                            Hint = "***",
                            ImageUrl = "honda.jpg",
                            IsSucceed = false,
                            Level = "Level 3",
                            Name = "Honda",
                            Point = 0
                        },
                        new
                        {
                            Id = "2D25E94CB5AE43BB8D8A55B805E48818",
                            Hint = "***",
                            ImageUrl = "nikon.jpg",
                            IsSucceed = false,
                            Level = "Level 3",
                            Name = "Nikon",
                            Point = 0
                        },
                        new
                        {
                            Id = "6AF0769F619E40C7A5631ED7A46B893F",
                            Hint = "***",
                            ImageUrl = "Pixar.jpg",
                            IsSucceed = false,
                            Level = "Level 3",
                            Name = "Pixar",
                            Point = 0
                        },
                        new
                        {
                            Id = "492B0D5909704D3E8319677A18F19F71",
                            Hint = "***",
                            ImageUrl = "puma.jpg",
                            IsSucceed = false,
                            Level = "Level 3",
                            Name = "Puma",
                            Point = 0
                        },
                        new
                        {
                            Id = "9AD6FD4C2DEA4A08AFA9EE05EDE4FF41",
                            Hint = "***",
                            ImageUrl = "renault.jpg",
                            IsSucceed = false,
                            Level = "Level 3",
                            Name = "Renault",
                            Point = 0
                        },
                        new
                        {
                            Id = "0B48A3DD753E45DD842D1F0D11031E22",
                            Hint = "***",
                            ImageUrl = "seat.jpg",
                            IsSucceed = false,
                            Level = "Level 3",
                            Name = "Seat",
                            Point = 0
                        },
                        new
                        {
                            Id = "7624EA82F6A845E6A770DE63D63F7312",
                            Hint = "***",
                            ImageUrl = "seven-eleven.jpg",
                            IsSucceed = false,
                            Level = "Level 3",
                            Name = "Seven Eleven",
                            Point = 0
                        },
                        new
                        {
                            Id = "471024E886284B32805A4860C416C8D5",
                            Hint = "***",
                            ImageUrl = "tag-heuer.jpg",
                            IsSucceed = false,
                            Level = "Level 3",
                            Name = "Tag Heuer",
                            Point = 0
                        },
                        new
                        {
                            Id = "BCF463F6B7724AFCB8F47A110E9B4BAA",
                            Hint = "***",
                            ImageUrl = "woolmark.jpg",
                            IsSucceed = false,
                            Level = "Level 3",
                            Name = "Woolmark",
                            Point = 0
                        },
                        new
                        {
                            Id = "A4CA923E46314ED0B909B6C5CB9DB151",
                            Hint = "***",
                            ImageUrl = "xbox.jpg",
                            IsSucceed = false,
                            Level = "Level 3",
                            Name = "Xbox",
                            Point = 0
                        },
                        new
                        {
                            Id = "E6CA560123BD422895104598BEC34596",
                            Hint = "***",
                            ImageUrl = "xerox.jpg",
                            IsSucceed = false,
                            Level = "Level 3",
                            Name = "Xerox",
                            Point = 0
                        },
                        new
                        {
                            Id = "B43A6FC703D14E23A646D2686668A4F0",
                            Hint = "***",
                            ImageUrl = "yellow-pages.jpg",
                            IsSucceed = false,
                            Level = "Level 3",
                            Name = "Yellow Pages",
                            Point = 0
                        },
                        new
                        {
                            Id = "8FBBBE6B5A5246EDAF162D817088B523",
                            Hint = "***",
                            ImageUrl = "acdc.jpg",
                            IsSucceed = false,
                            Level = "Level 4",
                            Name = "ACDC",
                            Point = 0
                        },
                        new
                        {
                            Id = "1152A4419AB8417BA4F332E515E60B2B",
                            Hint = "***",
                            ImageUrl = "benetton.jpg",
                            IsSucceed = false,
                            Level = "Level 4",
                            Name = "Benetton",
                            Point = 0
                        },
                        new
                        {
                            Id = "8A535414A956479D89CA843CDEC00CAF",
                            Hint = "***",
                            ImageUrl = "budweiser.jpg",
                            IsSucceed = false,
                            Level = "Level 4",
                            Name = "Budweiser",
                            Point = 0
                        },
                        new
                        {
                            Id = "F98E6639F1B94AC69D27A5D6F5F46660",
                            Hint = "***",
                            ImageUrl = "cartoon-network.jpg",
                            IsSucceed = false,
                            Level = "Level 4",
                            Name = "Cartoon Network",
                            Point = 0
                        },
                        new
                        {
                            Id = "93A5944F5E174BC2ABCDEE0CB6A7F012",
                            Hint = "***",
                            ImageUrl = "cheerios.jpg",
                            IsSucceed = false,
                            Level = "Level 4",
                            Name = "Cheerios",
                            Point = 0
                        },
                        new
                        {
                            Id = "B59C247344974BDAA41043E15E5F020C",
                            Hint = "***",
                            ImageUrl = "discovery.jpg",
                            IsSucceed = false,
                            Level = "Level 4",
                            Name = "Discovery",
                            Point = 0
                        },
                        new
                        {
                            Id = "6B3EF3D7847C4E7797EB69AB267009F2",
                            Hint = "***",
                            ImageUrl = "dove.jpg",
                            IsSucceed = false,
                            Level = "Level 4",
                            Name = "Dove",
                            Point = 0
                        },
                        new
                        {
                            Id = "3F96E8FD0CBA4015BC7490A317E1F70F",
                            Hint = "***",
                            ImageUrl = "durex.jpg",
                            IsSucceed = false,
                            Level = "Level 4",
                            Name = "Durex",
                            Point = 0
                        },
                        new
                        {
                            Id = "FA19D31AB8EE4A27A99D691918AA0EFA",
                            Hint = "***",
                            ImageUrl = "fisherprice.jpg",
                            IsSucceed = false,
                            Level = "Level 4",
                            Name = "Fisherprice",
                            Point = 0
                        },
                        new
                        {
                            Id = "886734374CE54A1FA8C45C141C02FB1D",
                            Hint = "***",
                            ImageUrl = "fosters.jpg",
                            IsSucceed = false,
                            Level = "Level 4",
                            Name = "Fosters",
                            Point = 0
                        },
                        new
                        {
                            Id = "378D75B8800A4EB2BF8F5EEF1EE186B8",
                            Hint = "***",
                            ImageUrl = "illy.jpg",
                            IsSucceed = false,
                            Level = "Level 4",
                            Name = "Illy",
                            Point = 0
                        },
                        new
                        {
                            Id = "D8A00F327C6F4C849CBF7169AF738B79",
                            Hint = "***",
                            ImageUrl = "john-deere.jpg",
                            IsSucceed = false,
                            Level = "Level 4",
                            Name = "John Deere",
                            Point = 0
                        },
                        new
                        {
                            Id = "49C5595139DE4441BD07A7A827B66115",
                            Hint = "***",
                            ImageUrl = "kia.jpg",
                            IsSucceed = false,
                            Level = "Level 4",
                            Name = "Kia",
                            Point = 0
                        },
                        new
                        {
                            Id = "D6DFADB6695A4977B72A169E40D9DAE3",
                            Hint = "***",
                            ImageUrl = "kleenex.jpg",
                            IsSucceed = false,
                            Level = "Level 4",
                            Name = "Kleenex",
                            Point = 0
                        },
                        new
                        {
                            Id = "3830F1DD03BB442888B1FBFCABCAE6DC",
                            Hint = "***",
                            ImageUrl = "kraft.jpg",
                            IsSucceed = false,
                            Level = "Level 4",
                            Name = "Kraft",
                            Point = 0
                        },
                        new
                        {
                            Id = "E008EF7DF2664293BF6E7C0C11366268",
                            Hint = "***",
                            ImageUrl = "land-rover.jpg",
                            IsSucceed = false,
                            Level = "Level 4",
                            Name = "Land Rover",
                            Point = 0
                        },
                        new
                        {
                            Id = "6DE509FB1B134ADC88A25CE408AAF1E6",
                            Hint = "***",
                            ImageUrl = "linkedin.jpg",
                            IsSucceed = false,
                            Level = "Level 4",
                            Name = "Linkedin",
                            Point = 0
                        },
                        new
                        {
                            Id = "8B96C0935A3C4CE48B77188F329CB5BC",
                            Hint = "***",
                            ImageUrl = "malibu.jpg",
                            IsSucceed = false,
                            Level = "Level 4",
                            Name = "Malibu",
                            Point = 0
                        },
                        new
                        {
                            Id = "8A5E4D27DA6247E4BCAB4D68A19F2356",
                            Hint = "***",
                            ImageUrl = "umbro.jpg",
                            IsSucceed = false,
                            Level = "Level 4",
                            Name = "Umbro",
                            Point = 0
                        },
                        new
                        {
                            Id = "A9AAFFFC4F0F4E34AC348477686FA9C3",
                            Hint = "***",
                            ImageUrl = "wifi.jpg",
                            IsSucceed = false,
                            Level = "Level 4",
                            Name = "Wifi",
                            Point = 0
                        },
                        new
                        {
                            Id = "6AC8E2C97FED4054AB4559F961C4658B",
                            Hint = "***",
                            ImageUrl = "air-jordan.jpg",
                            IsSucceed = false,
                            Level = "Level 5",
                            Name = "Air Jordan",
                            Point = 0
                        },
                        new
                        {
                            Id = "CDF8EA6B8E954D7BA8AD4CB6967E63FD",
                            Hint = "***",
                            ImageUrl = "android.jpg",
                            IsSucceed = false,
                            Level = "Level 5",
                            Name = "Android",
                            Point = 0
                        },
                        new
                        {
                            Id = "9F5B076EB83643B596B53C544079BAD5",
                            Hint = "***",
                            ImageUrl = "asus.jpg",
                            IsSucceed = false,
                            Level = "Level 5",
                            Name = "Asus",
                            Point = 0
                        },
                        new
                        {
                            Id = "056395EC6473402899A429B466B7A91C",
                            Hint = "***",
                            ImageUrl = "atari.jpg",
                            IsSucceed = false,
                            Level = "Level 5",
                            Name = "Atari",
                            Point = 0
                        },
                        new
                        {
                            Id = "BE4D307949544E54B4B8C7559C801230",
                            Hint = "***",
                            ImageUrl = "avery.jpg",
                            IsSucceed = false,
                            Level = "Level 5",
                            Name = "Avery",
                            Point = 0
                        },
                        new
                        {
                            Id = "2CCB469B650C45908F6619F2AF289574",
                            Hint = "***",
                            ImageUrl = "chiquita.jpg",
                            IsSucceed = false,
                            Level = "Level 5",
                            Name = "Chiquita",
                            Point = 0
                        },
                        new
                        {
                            Id = "72B031F7B4AC446F87017160253AC9C7",
                            Hint = "***",
                            ImageUrl = "chupa-chups.jpg",
                            IsSucceed = false,
                            Level = "Level 5",
                            Name = "Chupa Chups",
                            Point = 0
                        },
                        new
                        {
                            Id = "4A3FEAC780BD40FE9631C92A8D1B5D3B",
                            Hint = "***",
                            ImageUrl = "delta.jpg",
                            IsSucceed = false,
                            Level = "Level 5",
                            Name = "Delta",
                            Point = 0
                        },
                        new
                        {
                            Id = "7290606630024ABFBC19852CD91B674E",
                            Hint = "***",
                            ImageUrl = "fiat.jpg",
                            IsSucceed = false,
                            Level = "Level 5",
                            Name = "Fiat",
                            Point = 0
                        },
                        new
                        {
                            Id = "454272D2ED1B42B9BF91A738099B48F7",
                            Hint = "***",
                            ImageUrl = "fsc.jpg",
                            IsSucceed = false,
                            Level = "Level 5",
                            Name = "Fsc",
                            Point = 0
                        },
                        new
                        {
                            Id = "5EB6B239F7434816AF8ED5DF14F0B4B6",
                            Hint = "***",
                            ImageUrl = "lays.jpg",
                            IsSucceed = false,
                            Level = "Level 5",
                            Name = "Lays",
                            Point = 0
                        },
                        new
                        {
                            Id = "F21376B08ADC47C58B6830FDBD23B773",
                            Hint = "***",
                            ImageUrl = "nespresso.jpg",
                            IsSucceed = false,
                            Level = "Level 5",
                            Name = "Nespresso",
                            Point = 0
                        },
                        new
                        {
                            Id = "5477F9D7C75A4D0582C6448907EC042F",
                            Hint = "***",
                            ImageUrl = "nestle.jpg",
                            IsSucceed = false,
                            Level = "Level 5",
                            Name = "Nestle",
                            Point = 0
                        },
                        new
                        {
                            Id = "08C731497B4B4A389EB1968158E6E2AC",
                            Hint = "***",
                            ImageUrl = "nivea.jpg",
                            IsSucceed = false,
                            Level = "Level 5",
                            Name = "Nivea",
                            Point = 0
                        },
                        new
                        {
                            Id = "06B1DB46F9254CB48DBEBCA96B6FCF7F",
                            Hint = "***",
                            ImageUrl = "pampers.jpg",
                            IsSucceed = false,
                            Level = "Level 5",
                            Name = "Pampers",
                            Point = 0
                        },
                        new
                        {
                            Id = "99840B7DB6F14207A9D4D528EC2D0DAF",
                            Hint = "***",
                            ImageUrl = "sheraton.jpg",
                            IsSucceed = false,
                            Level = "Level 5",
                            Name = "Sheraton",
                            Point = 0
                        },
                        new
                        {
                            Id = "523375D0093B4E349C9275FBEFFE3400",
                            Hint = "***",
                            ImageUrl = "showtime.jpg",
                            IsSucceed = false,
                            Level = "Level 5",
                            Name = "Showtime",
                            Point = 0
                        },
                        new
                        {
                            Id = "860D583A41424F9F9958A529A8277398",
                            Hint = "***",
                            ImageUrl = "target.jpg",
                            IsSucceed = false,
                            Level = "Level 5",
                            Name = "Target",
                            Point = 0
                        },
                        new
                        {
                            Id = "A67FE8FEB2914AF69BE93ECA8B53ED2A",
                            Hint = "***",
                            ImageUrl = "tictac.jpg",
                            IsSucceed = false,
                            Level = "Level 5",
                            Name = "Tictac",
                            Point = 0
                        },
                        new
                        {
                            Id = "B7E6EF634E5142E4B6DE4782538BE004",
                            Hint = "***",
                            ImageUrl = "total.jpg",
                            IsSucceed = false,
                            Level = "Level 5",
                            Name = "Total",
                            Point = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
